### ISSUE TITLE
Feature request: Setting max / initial heap size with percent

### ISSUE THREAD

**Issue by jindrapetrik** [lordmulder/Launch5j#1]
Hello,
Original Launch4j has a feature that you can select maximum and initial heap size of launched Java App with percent of current memory available.
In launch5j, it can be only set with -Xmx and -Xms to concrete value in MBytes, but not as percentage.

Percentage value is useful as I want my app to get as much max value as is available and if I set the fixed value, then that value can be too low or even invalid if its larger than available memory.

I am not a C programmer,
but it seems that Launch4j does it this way: https://github.com/fbergmann/launch4j/blob/9ea2d07bd04257c1888f72cc2ae851749a3effc5/head_src/head.c#L483

So maybe something similar?

Thank you in advance for consideration.

**Comment by jindrapetrik** [comment]
I forked your project and try to modify the percentage to fit my needs - you can see my commit in https://github.com/jindrapetrik/Launch5j/commit/c7920180d3835a2648806c48ac8523c9e4827fa0 in mempercent branch.
This is now hardcoded to 100 percent of memory. It should be configurable in the resources as other config.

Just a suggestion for you. 
It works for me as is now for my project. I don't force you to include it.

**Comment by lordmulder** [comment]
Hi. I think your suggested code has a memory leak, because "old" `jvm_extra_args` value is never freed.

Also I think the code should be structured a little bit different.

Finally, we should have an option, in the resource section, to set the minimum/maximum heap size (in percent).

Please try with this version and tell me if it works for you:
[**launch5j-bin.2023-03-26.zip**](https://github.com/lordmulder/Launch5j/files/11072226/launch5j-bin.2023-03-26.zip)

(the new version also builds with an up-to-date Mingw-w64 again)

Regards.

**Comment by jindrapetrik** [comment]
Hi, sorry for the leak, I do not program in C language much.

The version you attached seems to work fine for me,
but I have a question:
Is there a need to set both of the values at the same time? minimum and maximum?
("This option must be specified together with ID_STR_HEAPMIN")

I was using launch4j only to set the maximum value,
I don't think I need to specify its minimum value,
I don't even know what the setting of the minimum does to the JVM.
I would prefer the minimum to stay the default for my app.
Surely some users will like the option to set the minimum,
but why to force it?

Is it a technical problem for the program? To set these two values independently?

Anyway, thank you for the update!

**Comment by lordmulder** [comment]
Option `-Xms` sets the initial (minimum) size of the heap space, allocated when the JVM is starting up.

Option `-Xmx` sets the maximum size to which the heap space may grow. Heap still only grows above its initial size, if needed.

Always setting *both* values makes things a bit easier, but I have removed the limitation now:
[**launch5j-bin.2023-03-26.r2.zip**](https://github.com/lordmulder/Launch5j/files/11072727/launch5j-bin.2023-03-26.r2.zip)

--------

**Note:** If you don't set `-Xms` or `-Xmx` explicitly, the JVM simply uses a default value:

> ## Default Heap Size
> Unless the initial and maximum heap sizes are specified on the command line, they are calculated based on the amount of memory on the machine.
> 
> ### Client JVM Default Initial and Maximum Heap Sizes
> The default maximum heap size is half of the physical memory up to a physical memory size of 192 megabytes (MB) and otherwise one fourth of the physical memory up to a physical memory size of 1 gigabyte (GB).
> For example, if your computer has 128 MB of physical memory, then the maximum heap size is 64 MB, and greater than or equal to 1 GB of physical memory results in a maximum heap size of 256 MB.
> The maximum heap size is not actually used by the JVM unless your program creates enough objects to require it. A much smaller amount, called the initial heap size, is allocated during JVM initialization. This amount is at least 8 MB and otherwise 1/64th of physical memory up to a physical memory size of 1 GB.
> The maximum amount of space allocated to the young generation is one third of the total heap size.
> 
> ### Server JVM Default Initial and Maximum Heap Sizes
> The default initial and maximum heap sizes work similarly on the server JVM as it does on the client JVM, except that the default values can go higher. On 32-bit JVMs, the default maximum heap size can be up to 1 GB if there is 4 GB or more of physical memory. On 64-bit JVMs, the default maximum heap size can be up to 32 GB if there is 128 GB or more of physical memory. You can always set a higher or lower initial and maximum heap by specifying those values directly; see the next section.

**Comment by jindrapetrik** [comment]
Thank you very much, the 2023-03-26.r2 version works as intended.
I am fully satisfied.

**Comment by lordmulder** [comment]
I have now added an additional check to limit the heap size to 1024 MB when a 32-Bit JVM is detected:
[**launch5j-bin.2023-03-26.r3.zip**](https://github.com/lordmulder/Launch5j/files/11073036/launch5j-bin.2023-03-26.r3.zip)

**Note:** In my test, 32-Bit `java.exe` with `-Xms` or `-Xmx` set to more than `1024m` will error out; even `1280m` won't work:

![grafik](https://user-images.githubusercontent.com/470590/227803372-0c6f455a-3d75-4ced-a67d-85b5aaa0df63.png)

**Comment by jindrapetrik** [comment]
Ok, thank you.
