### ISSUE TITLE
App changes current working directory.

### ISSUE THREAD

**Issue by jindrapetrik** [lordmulder/Launch5j#2]
My java app uses your launcher.
I have a problem.
My app accepts filename parameters.

I would like to execute the launcher from other directory than app directory, but I'd like to have the file paths relative to the current working directory.

Example:
I place `run.jar` and `run.exe` in the directory `C:\myapp\`.
Then I go to the commandline and change directory with `cd` into `C:\otherdir\` where I have my data files `file1.bin`, `file2.bin`.
I'd like to pass the files as arguments to the app relatively to `otherdir`, but it fails because the launcher changes current working directory to the app dir.

```cmd
cd C:\otherdir\
C:\myapp\run.exe file1.bin file2.bin
```
Which assumes `file1.bin` and `file2.bin` are in the directory `C:\myapp\` because the launcher changes CWD,
but they are in `C:\otherdir\` so the opening of them fails.

I hope I am explaining it enough so you get what I want.

I think the launcher should not change current working directory or it should be configurable.

The app in the attachment just prints out current working directory.
It should print `C:\otherdir\` in the example, but prints `C:\myapp\`.

It should behave as:
```cmd
cd C:\otherdir\
java -jar C:\myapp\run.jar file1.bin file2.bin
```

Thank you very much for consideration of the change!

[run.zip](https://github.com/user-attachments/files/17167582/run.zip)

**Comment by lordmulder** [comment]
Hello.

I think you can simply comment line [#1698](https://github.com/lordmulder/Launch5j/blob/9d27eb5a98edd1b3c4e5129f01c33c68225c4ceb/src/head.c#L1698) to get the desired behavior.

Regards.

**Comment by lordmulder** [comment]
I have added new runtime option **`ID_STR_NSETCWD`** (**`0x08`**) that can be used to control whether the current directory should be set to the directory where the executable file is located: https://github.com/lordmulder/Launch5j/commit/ba821fa382fb134195ecced89ea8e1d68e569fd4

You can try with this build (please see the included README file for details):
[launch5j-bin.2024-09-29.zip](https://github.com/user-attachments/files/17179197/launch5j-bin.2024-09-29.zip)

**Comment by jindrapetrik** [comment]
Thank you very much for the update.
I tried it, set the string index 8 via Resource Hacker to "1",
but unfortunately, the result was the same - the app (try the app in run.zip) printed out the app dir, not the data dir I was in.

I guess this needs to be updated too:
```
if (!CreateProcessW(NULL, (LPWSTR)command_line, NULL, NULL, FALSE, 0U, NULL, executable_directory /*THIS*/, &startup_info, &process_info))
```
Could you try it?
Thanks in advance.

**Comment by lordmulder** [comment]
You are right. The invocation of `CreateProcessW()` needs to be adjusted too: https://github.com/lordmulder/Launch5j/commit/02931280d0955ffad5a68a120147d33d9077f2e4

Please try with this build:
[launch5j-bin.2024-09-29.r2.zip](https://github.com/user-attachments/files/17179587/launch5j-bin.2024-09-29.r2.zip)

**Comment by jindrapetrik** [comment]
It works, yay!
Thank you very much!
